export type GalleryPhoto = {
  id: string;
  label: string;
  credit: string;
  src: string;
  page: string;
};

/**
 * Recognizable public-domain pictures.
 * NASA files are US government work. Museum files are CC0 or public domain.
 */
export const GALLERY: GalleryPhoto[] = [
  { id: "moonwalk", label: "Moonwalk", credit: "NASA", src: "/gallery/moonwalk.jpg", page: "https://en.wikipedia.org/wiki/Apollo_11" },
  { id: "earthrise", label: "Earthrise", credit: "NASA", src: "/gallery/earthrise.jpg", page: "https://en.wikipedia.org/wiki/Earthrise" },
  { id: "marble", label: "Blue Marble", credit: "NASA", src: "/gallery/marble.jpg", page: "https://en.wikipedia.org/wiki/The_Blue_Marble" },
  { id: "pillars", label: "Pillars of Creation", credit: "NASA / ESA", src: "/gallery/pillars.jpg", page: "https://en.wikipedia.org/wiki/Pillars_of_Creation" },
  { id: "saturn", label: "Saturn", credit: "NASA / JPL", src: "/gallery/saturn.jpg", page: "https://en.wikipedia.org/wiki/Saturn" },
  { id: "mona-lisa", label: "Mona Lisa", credit: "Leonardo da Vinci", src: "/gallery/mona-lisa.jpg", page: "https://en.wikipedia.org/wiki/Mona_Lisa" },
  { id: "starry-night", label: "Starry Night", credit: "Vincent van Gogh", src: "/gallery/starry-night.jpg", page: "https://en.wikipedia.org/wiki/The_Starry_Night" },
  { id: "sunflowers", label: "Sunflowers", credit: "Vincent van Gogh", src: "/gallery/sunflowers.jpg", page: "https://en.wikipedia.org/wiki/Sunflowers_(Van_Gogh_series)" },
  { id: "cafe-terrace", label: "Café Terrace at Night", credit: "Vincent van Gogh", src: "/gallery/cafe-terrace.jpg", page: "https://en.wikipedia.org/wiki/Caf%C3%A9_Terrace_at_Night" },
  { id: "bedroom", label: "The Bedroom", credit: "Vincent van Gogh", src: "/gallery/bedroom.jpg", page: "https://en.wikipedia.org/wiki/Bedroom_in_Arles" },
  { id: "irises", label: "Irises", credit: "Vincent van Gogh", src: "/gallery/irises.jpg", page: "https://en.wikipedia.org/wiki/Irises_(painting)" },
  { id: "almond-blossom", label: "Almond Blossom", credit: "Vincent van Gogh", src: "/gallery/almond-blossom.jpg", page: "https://en.wikipedia.org/wiki/Almond_Blossoms" },
  { id: "great-wave", label: "The Great Wave", credit: "Katsushika Hokusai", src: "/gallery/great-wave.jpg", page: "https://en.wikipedia.org/wiki/The_Great_Wave_off_Kanagawa" },
  { id: "pearl-earring", label: "Girl with a Pearl Earring", credit: "Johannes Vermeer", src: "/gallery/pearl-earring.jpg", page: "https://en.wikipedia.org/wiki/Girl_with_a_Pearl_Earring" },
  { id: "milkmaid", label: "The Milkmaid", credit: "Johannes Vermeer", src: "/gallery/milkmaid.jpg", page: "https://en.wikipedia.org/wiki/The_Milkmaid_(Vermeer)" },
  { id: "astronomer", label: "The Astronomer", credit: "Johannes Vermeer", src: "/gallery/astronomer.jpg", page: "https://en.wikipedia.org/wiki/The_Astronomer_(Vermeer)" },
  { id: "birth-of-venus", label: "Birth of Venus", credit: "Sandro Botticelli", src: "/gallery/birth-of-venus.jpg", page: "https://en.wikipedia.org/wiki/The_Birth_of_Venus" },
  { id: "primavera", label: "Primavera", credit: "Sandro Botticelli", src: "/gallery/primavera.jpg", page: "https://en.wikipedia.org/wiki/Primavera_(Botticelli)" },
  { id: "creation-of-adam", label: "Creation of Adam", credit: "Michelangelo", src: "/gallery/creation-of-adam.jpg", page: "https://en.wikipedia.org/wiki/The_Creation_of_Adam" },
  { id: "school-of-athens", label: "The School of Athens", credit: "Raphael", src: "/gallery/school-of-athens.jpg", page: "https://en.wikipedia.org/wiki/The_School_of_Athens" },
  { id: "vitruvian", label: "Vitruvian Man", credit: "Leonardo da Vinci", src: "/gallery/vitruvian.jpg", page: "https://en.wikipedia.org/wiki/Vitruvian_Man" },
  { id: "the-scream", label: "The Scream", credit: "Edvard Munch", src: "/gallery/the-scream.jpg", page: "https://en.wikipedia.org/wiki/The_Scream" },
  { id: "the-kiss", label: "The Kiss", credit: "Gustav Klimt", src: "/gallery/the-kiss.jpg", page: "https://en.wikipedia.org/wiki/The_Kiss_(Klimt)" },
  { id: "wanderer", label: "Wanderer above the Sea of Fog", credit: "Caspar David Friedrich", src: "/gallery/wanderer.jpg", page: "https://en.wikipedia.org/wiki/Wanderer_above_the_Sea_of_Fog" },
  { id: "water-lilies", label: "Water Lilies", credit: "Claude Monet", src: "/gallery/water-lilies.jpg", page: "https://en.wikipedia.org/wiki/Water_Lilies_(Monet_series)" },
  { id: "impression-sunrise", label: "Impression, Sunrise", credit: "Claude Monet", src: "/gallery/impression-sunrise.jpg", page: "https://en.wikipedia.org/wiki/Impression,_Sunrise" },
  { id: "parasol", label: "Woman with a Parasol", credit: "Claude Monet", src: "/gallery/parasol.jpg", page: "https://en.wikipedia.org/wiki/Woman_with_a_Parasol_%E2%80%93_Madame_Monet_and_Her_Son" },
  { id: "grande-jatte", label: "A Sunday on La Grande Jatte", credit: "Georges Seurat", src: "/gallery/grande-jatte.jpg", page: "https://en.wikipedia.org/wiki/A_Sunday_Afternoon_on_the_Island_of_La_Grande_Jatte" },
  { id: "boating-party", label: "Luncheon of the Boating Party", credit: "Pierre-Auguste Renoir", src: "/gallery/boating-party.jpg", page: "https://en.wikipedia.org/wiki/Luncheon_of_the_Boating_Party" },
  { id: "night-watch", label: "The Night Watch", credit: "Rembrandt", src: "/gallery/night-watch.jpg", page: "https://en.wikipedia.org/wiki/The_Night_Watch" },
  { id: "las-meninas", label: "Las Meninas", credit: "Diego Velázquez", src: "/gallery/las-meninas.jpg", page: "https://en.wikipedia.org/wiki/Las_Meninas" },
  { id: "arnolfini", label: "Arnolfini Portrait", credit: "Jan van Eyck", src: "/gallery/arnolfini.jpg", page: "https://en.wikipedia.org/wiki/Arnolfini_Portrait" },
  { id: "earthly-delights", label: "Garden of Earthly Delights", credit: "Hieronymus Bosch", src: "/gallery/earthly-delights.jpg", page: "https://en.wikipedia.org/wiki/The_Garden_of_Earthly_Delights" },
  { id: "babel", label: "The Tower of Babel", credit: "Pieter Bruegel the Elder", src: "/gallery/babel.jpg", page: "https://en.wikipedia.org/wiki/The_Tower_of_Babel_(Bruegel)" },
  { id: "hunters", label: "Hunters in the Snow", credit: "Pieter Bruegel the Elder", src: "/gallery/hunters.jpg", page: "https://en.wikipedia.org/wiki/The_Hunters_in_the_Snow" },
  { id: "liberty", label: "Liberty Leading the People", credit: "Eugène Delacroix", src: "/gallery/liberty.jpg", page: "https://en.wikipedia.org/wiki/Liberty_Leading_the_People" },
  { id: "napoleon", label: "Napoleon Crossing the Alps", credit: "Jacques-Louis David", src: "/gallery/napoleon.jpg", page: "https://en.wikipedia.org/wiki/Napoleon_Crossing_the_Alps" },
  { id: "washington", label: "Washington Crossing the Delaware", credit: "Emanuel Leutze", src: "/gallery/washington.jpg", page: "https://en.wikipedia.org/wiki/Washington_Crossing_the_Delaware_(1851_painting)" },
  { id: "temeraire", label: "The Fighting Temeraire", credit: "J. M. W. Turner", src: "/gallery/temeraire.jpg", page: "https://en.wikipedia.org/wiki/The_Fighting_Temeraire" },
  { id: "ophelia", label: "Ophelia", credit: "John Everett Millais", src: "/gallery/ophelia.jpg", page: "https://en.wikipedia.org/wiki/Ophelia_(painting)" },
  { id: "shalott", label: "The Lady of Shalott", credit: "John William Waterhouse", src: "/gallery/shalott.jpg", page: "https://en.wikipedia.org/wiki/The_Lady_of_Shalott_(painting)" },
  { id: "the-swing", label: "The Swing", credit: "Jean-Honoré Fragonard", src: "/gallery/the-swing.jpg", page: "https://en.wikipedia.org/wiki/The_Swing_(Fragonard)" },
  { id: "olympia", label: "Olympia", credit: "Édouard Manet", src: "/gallery/olympia.jpg", page: "https://en.wikipedia.org/wiki/Olympia_(Manet)" },
  { id: "gleaners", label: "The Gleaners", credit: "Jean-François Millet", src: "/gallery/gleaners.jpg", page: "https://en.wikipedia.org/wiki/The_Gleaners" },
  { id: "moulin-rouge", label: "At the Moulin Rouge", credit: "Henri de Toulouse-Lautrec", src: "/gallery/moulin-rouge.jpg", page: "https://en.wikipedia.org/wiki/At_the_Moulin_Rouge" },
  { id: "whistlers-mother", label: "Whistler's Mother", credit: "James McNeill Whistler", src: "/gallery/whistlers-mother.jpg", page: "https://en.wikipedia.org/wiki/Whistler%27s_Mother" },
  { id: "american-gothic", label: "American Gothic", credit: "Grant Wood", src: "/gallery/american-gothic.jpg", page: "https://en.wikipedia.org/wiki/American_Gothic" },
  { id: "black-square", label: "Black Square", credit: "Kazimir Malevich", src: "/gallery/black-square.jpg", page: "https://en.wikipedia.org/wiki/Black_Square_(painting)" },
  { id: "migrant-mother", label: "Migrant Mother", credit: "Dorothea Lange", src: "/gallery/migrant-mother.jpg", page: "https://en.wikipedia.org/wiki/Migrant_Mother" },
  { id: "lincoln", label: "Abraham Lincoln", credit: "Alexander Gardner", src: "/gallery/lincoln.jpg", page: "https://en.wikipedia.org/wiki/Abraham_Lincoln" },
  { id: "virgin-rocks", label: "Virgin of the Rocks", credit: "Leonardo da Vinci", src: "/gallery/virgin-rocks.jpg", page: "https://en.wikipedia.org/wiki/Virgin_of_the_Rocks" },
  { id: "last-supper", label: "The Last Supper", credit: "Giampietrino, after Leonardo da Vinci", src: "/gallery/last-supper.jpg", page: "https://en.wikipedia.org/wiki/The_Last_Supper_(Leonardo)" },
  { id: "wheat-cypresses", label: "Wheat Field with Cypresses", credit: "Vincent van Gogh", src: "/gallery/wheat-cypresses.jpg", page: "https://www.metmuseum.org/art/collection/search/436535" },
  { id: "self-portrait-gogh", label: "Self-Portrait with a Straw Hat (obverse: The Potato Peeler)", credit: "Vincent van Gogh", src: "/gallery/self-portrait-gogh.jpg", page: "https://www.metmuseum.org/art/collection/search/436532" },
  { id: "madame-x", label: "Madame X (Virginie Amélie Avegno Gautreau)", credit: "John Singer Sargent", src: "/gallery/madame-x.jpg", page: "https://www.metmuseum.org/art/collection/search/12127" },
  { id: "gulf-stream", label: "The Gulf Stream", credit: "Winslow Homer", src: "/gallery/gulf-stream.jpg", page: "https://www.metmuseum.org/art/collection/search/11122" },
  { id: "water-lilies-aic", label: "Water Lilies (Agapanthus)", credit: "Claude Monet", src: "/gallery/water-lilies-aic.jpg", page: "https://clevelandart.org/art/1960.81" },
  { id: "asnieres", label: "Study for 'Bathers at Asnières'", credit: "Georges Seurat", src: "/gallery/asnieres.jpg", page: "https://clevelandart.org/art/1958.51" },
  { id: "dance-class", label: "The Dance Class", credit: "Edgar Degas", src: "/gallery/dance-class.jpg", page: "https://www.metmuseum.org/art/collection/search/438817" },
  { id: "ballet-rehearsal", label: "The Rehearsal of the Ballet Onstage", credit: "Edgar Degas", src: "/gallery/ballet-rehearsal.jpg", page: "https://www.metmuseum.org/art/collection/search/436155" },
  { id: "card-players", label: "The Card Players", credit: "Paul Cézanne", src: "/gallery/card-players.jpg", page: "https://www.metmuseum.org/art/collection/search/435868" },
  { id: "sainte-victoire", label: "Mont Sainte-Victoire and the Viaduct of the Arc River Valley", credit: "Paul Cézanne", src: "/gallery/sainte-victoire.jpg", page: "https://www.metmuseum.org/art/collection/search/435877" },
  { id: "apples", label: "Still Life with Apples and a Pot of Primroses", credit: "Paul Cézanne", src: "/gallery/apples.jpg", page: "https://www.metmuseum.org/art/collection/search/435882" },
  { id: "melencolia", label: "Melencolia I", credit: "Albrecht Dürer", src: "/gallery/melencolia.jpg", page: "https://www.metmuseum.org/art/collection/search/336228" },
  { id: "nasa-pia14417", label: "Weighing in on the Dumbbell Nebula", credit: "NASA", src: "/gallery/nasa-pia14417.jpg", page: "https://images.nasa.gov/details/PIA14417" },
  { id: "nasa-pia04216", label: "Ant Nebula", credit: "NASA", src: "/gallery/nasa-pia04216.jpg", page: "https://images.nasa.gov/details/PIA04216" },
  { id: "nasa-gsfc-20171208-archive-e001465", label: "Planetary Nebula", credit: "NASA", src: "/gallery/nasa-gsfc-20171208-archive-e001465.jpg", page: "https://images.nasa.gov/details/GSFC_20171208_Archive_e001465" },
  { id: "nasa-pia04220", label: "Trifid Nebula", credit: "NASA", src: "/gallery/nasa-pia04220.jpg", page: "https://images.nasa.gov/details/PIA04220" },
  { id: "nasa-pia04225", label: "N44C nebula", credit: "NASA", src: "/gallery/nasa-pia04225.jpg", page: "https://images.nasa.gov/details/PIA04225" },
  { id: "nasa-pia15658", label: "NGC 7293, the Helix Nebula", credit: "NASA", src: "/gallery/nasa-pia15658.jpg", page: "https://images.nasa.gov/details/PIA15658" },
  { id: "nasa-pia07902", label: "Planetary Nebula NGC 7293 also Known as the Helix Nebula", credit: "NASA", src: "/gallery/nasa-pia07902.jpg", page: "https://images.nasa.gov/details/PIA07902" },
  { id: "nasa-hubble-sees-the-wings-of-a-butterfly-the-twin-je", label: "The Twin Jet Nebula", credit: "NASA", src: "/gallery/nasa-hubble-sees-the-wings-of-a-butterfly-the-twin-je.jpg", page: "https://images.nasa.gov/details/hubble-sees-the-wings-of-a-butterfly-the-twin-jet-nebula_20283986193_o" },
  { id: "nasa-pia04200", label: "Doradus Nebula", credit: "NASA", src: "/gallery/nasa-pia04200.jpg", page: "https://images.nasa.gov/details/PIA04200" },
  { id: "nasa-pia04226", label: "Ghost Head Nebula", credit: "NASA", src: "/gallery/nasa-pia04226.jpg", page: "https://images.nasa.gov/details/PIA04226" },
  { id: "nasa-pia04227", label: "Orion Nebula and Bow Shock", credit: "NASA", src: "/gallery/nasa-pia04227.jpg", page: "https://images.nasa.gov/details/PIA04227" },
  { id: "nasa-pia04215", label: "Horsehead Nebula", credit: "NASA", src: "/gallery/nasa-pia04215.jpg", page: "https://images.nasa.gov/details/PIA04215" },
  { id: "nasa-pia04921", label: "Andromeda Galaxy", credit: "NASA", src: "/gallery/nasa-pia04921.jpg", page: "https://images.nasa.gov/details/PIA04921" },
  { id: "nasa-pia04634", label: "Galaxy NGC5474", credit: "NASA", src: "/gallery/nasa-pia04634.jpg", page: "https://images.nasa.gov/details/PIA04634" },
  { id: "nasa-pia07906", label: "Virgo Galaxy Cluster", credit: "NASA", src: "/gallery/nasa-pia07906.jpg", page: "https://images.nasa.gov/details/PIA07906" },
  { id: "nasa-pia04623", label: "Galaxy UGC10445", credit: "NASA", src: "/gallery/nasa-pia04623.jpg", page: "https://images.nasa.gov/details/PIA04623" },
  { id: "nasa-pia04635", label: "Galaxy NGC5962", credit: "NASA", src: "/gallery/nasa-pia04635.jpg", page: "https://images.nasa.gov/details/PIA04635" },
  { id: "nasa-pia04633", label: "Galaxy NGC5398", credit: "NASA", src: "/gallery/nasa-pia04633.jpg", page: "https://images.nasa.gov/details/PIA04633" },
  { id: "nasa-pia15656", label: "Portrait of a Galaxy Life", credit: "NASA", src: "/gallery/nasa-pia15656.jpg", page: "https://images.nasa.gov/details/PIA15656" },
  { id: "nasa-pia04629", label: "Galaxy Messier 83", credit: "NASA", src: "/gallery/nasa-pia04629.jpg", page: "https://images.nasa.gov/details/PIA04629" },
  { id: "nasa-pia04624", label: "Galaxy Centaurus A", credit: "NASA", src: "/gallery/nasa-pia04624.jpg", page: "https://images.nasa.gov/details/PIA04624" },
  { id: "nasa-pia04923", label: "Galaxy NGC 55", credit: "NASA", src: "/gallery/nasa-pia04923.jpg", page: "https://images.nasa.gov/details/PIA04923" },
  { id: "nasa-pia20695", label: "Frankenstein Galaxy", credit: "NASA", src: "/gallery/nasa-pia20695.jpg", page: "https://images.nasa.gov/details/PIA20695" },
  { id: "nasa-as12-46-6728", label: "Apollo 12 Mission image - Dark view of Astronaut Alan L. Bean climbing down the ladder of the Lunar Module (LM)", credit: "NASA", src: "/gallery/nasa-as12-46-6728.jpg", page: "https://images.nasa.gov/details/as12-46-6728" },
  { id: "nasa-s70-45521", label: "Astronaut Stuart A. Roosa, Apollo 14 Command Module pilot", credit: "NASA", src: "/gallery/nasa-s70-45521.jpg", page: "https://images.nasa.gov/details/S70-45521" },
  { id: "nasa-afrc2019-0244-18", label: "Former Apollo Astronaut Vance Brand", credit: "NASA", src: "/gallery/nasa-afrc2019-0244-18.jpg", page: "https://images.nasa.gov/details/AFRC2019-0244-18" },
  { id: "nasa-as17-162-24053", label: "Astronauts Evans and Cernan aboard the Apollo 17 spacecraft", credit: "NASA", src: "/gallery/nasa-as17-162-24053.jpg", page: "https://images.nasa.gov/details/as17-162-24053" },
  { id: "nasa-s70-45232", label: "Astronaut Alan B. Shepard Jr., Apollo 14 mission commander", credit: "NASA", src: "/gallery/nasa-s70-45232.jpg", page: "https://images.nasa.gov/details/S70-45232" },
  { id: "nasa-s67-37714", label: "Apollo astronaut geology training in Iceland - S67-37714", credit: "NASA", src: "/gallery/nasa-s67-37714.jpg", page: "https://images.nasa.gov/details/S67-37714" },
  { id: "nasa-as17-162-24049", label: "Astronaut Eugene Cernan sleeping aboard Apollo 17 spacecraft", credit: "NASA", src: "/gallery/nasa-as17-162-24049.jpg", page: "https://images.nasa.gov/details/as17-162-24049" },
  { id: "cma-1915-534", label: "Nathaniel Hurd", credit: "John Singleton Copley", src: "/gallery/cma-1915-534.jpg", page: "https://clevelandart.org/art/1915.534" },
  { id: "cma-1921-1239", label: "Portrait of Dora Wheeler", credit: "William Merritt Chase", src: "/gallery/cma-1921-1239.jpg", page: "https://clevelandart.org/art/1921.1239" },
  { id: "cma-1922-1133", label: "Stag at Sharkey's", credit: "George Bellows", src: "/gallery/cma-1922-1133.jpg", page: "https://clevelandart.org/art/1922.1133" },
  { id: "cma-1927-1984", label: "The Biglin Brothers Turning the Stake", credit: "Thomas Eakins", src: "/gallery/cma-1927-1984.jpg", page: "https://clevelandart.org/art/1927.1984" },
  { id: "cma-1928-8", label: "The Race Track (Death on a Pale Horse)", credit: "Albert Pinkham Ryder", src: "/gallery/cma-1928-8.jpg", page: "https://clevelandart.org/art/1928.8" },
  { id: "cma-1962-2", label: "Mme L . . . (Laure Borreau)", credit: "Gustave Courbet", src: "/gallery/cma-1962-2.jpg", page: "https://clevelandart.org/art/1962.2" },
  { id: "cma-1958-31", label: "Adeline Ravoux", credit: "Vincent van Gogh", src: "/gallery/cma-1958-31.jpg", page: "https://clevelandart.org/art/1958.31" },
  { id: "cma-1917-1335", label: "View of Schroon Mountain, Essex County, New York, After a Storm", credit: "Thomas Cole", src: "/gallery/cma-1917-1335.jpg", page: "https://clevelandart.org/art/1917.1335" },
  { id: "cma-1958-39", label: "The Red Kerchief", credit: "Claude Monet", src: "/gallery/cma-1958-39.jpg", page: "https://clevelandart.org/art/1958.39" },
  { id: "cma-1946-83", label: "Frieze of Dancers", credit: "Edgar Degas", src: "/gallery/cma-1946-83.jpg", page: "https://clevelandart.org/art/1946.83" },
  { id: "cma-1927-393", label: "Elizabeth Shewell West and Her Son, Raphael", credit: "Benjamin West", src: "/gallery/cma-1927-393.jpg", page: "https://clevelandart.org/art/1927.393" },
  { id: "cma-1999-173", label: "Portrait of Tieleman Roosterman", credit: "Frans Hals", src: "/gallery/cma-1999-173.jpg", page: "https://clevelandart.org/art/1999.173" },
  { id: "cma-1958-425", label: "Hunting near Hartenfels Castle", credit: "Lucas Cranach", src: "/gallery/cma-1958-425.jpg", page: "https://clevelandart.org/art/1958.425" },
  { id: "cma-1954-392", label: "A Genoese Lady with Her Child", credit: "Anthony van Dyck", src: "/gallery/cma-1954-392.jpg", page: "https://clevelandart.org/art/1954.392" },
  { id: "cma-1976-2", label: "The Crucifixion of Saint Andrew", credit: "Caravaggio", src: "/gallery/cma-1976-2.jpg", page: "https://clevelandart.org/art/1976.2" },
  { id: "cma-1942-647", label: "The Burning of the Houses of Lords and Commons, 16 October 1834", credit: "Joseph Mallord William Turner", src: "/gallery/cma-1942-647.jpg", page: "https://clevelandart.org/art/1942.647" },
  { id: "cma-1978-63", label: "In the Waves (Dans les Vagues)", credit: "Paul Gauguin", src: "/gallery/cma-1978-63.jpg", page: "https://clevelandart.org/art/1978.63" },
  { id: "cma-1959-190", label: "Diana and Her Nymphs Departing for the Hunt", credit: "Peter Paul Rubens", src: "/gallery/cma-1959-190.jpg", page: "https://clevelandart.org/art/1959.190" },
  { id: "cma-1956-578", label: "Sunny Autumn Day", credit: "George Inness", src: "/gallery/cma-1956-578.jpg", page: "https://clevelandart.org/art/1956.578" },
  { id: "cma-1944-90", label: "Portrait of a Woman", credit: "Rembrandt van Rijn", src: "/gallery/cma-1944-90.jpg", page: "https://clevelandart.org/art/1944.90" },
  { id: "cma-1947-209", label: "The Large Plane Trees (Road Menders at Saint-Rémy)", credit: "Vincent van Gogh", src: "/gallery/cma-1947-209.jpg", page: "https://clevelandart.org/art/1947.209" },
  { id: "cma-1961-39", label: "View of Florence", credit: "Thomas Cole", src: "/gallery/cma-1961-39.jpg", page: "https://clevelandart.org/art/1961.39" },
  { id: "cma-1972-48", label: "Branch Hill Pond, Hampstead", credit: "John Constable", src: "/gallery/cma-1972-48.jpg", page: "https://clevelandart.org/art/1972.48" },
  { id: "cma-1967-63", label: "Low Waterfall in a Wooded Landscape with a Dead Beech Tree", credit: "Jacob van Ruisdael", src: "/gallery/cma-1967-63.jpg", page: "https://clevelandart.org/art/1967.63" },
  { id: "cma-1926-1976", label: "Violette Heymann", credit: "Odilon Redon", src: "/gallery/cma-1926-1976.jpg", page: "https://clevelandart.org/art/1926.1976" },
  { id: "cma-1951-356", label: "Edge of the Woods Near L'Hermitage, Pontoise", credit: "Camille Pissarro", src: "/gallery/cma-1951-356.jpg", page: "https://clevelandart.org/art/1951.356" },
  { id: "cma-1998-168", label: "Portrait of Lisa Colt Curtis", credit: "John Singer Sargent", src: "/gallery/cma-1998-168.jpg", page: "https://clevelandart.org/art/1998.168" },
  { id: "cma-1966-49", label: "Wrestlers in a Circus", credit: "Ernst Ludwig Kirchner", src: "/gallery/cma-1966-49.jpg", page: "https://clevelandart.org/art/1966.49" },
  { id: "cma-1921-428", label: "Elizabeth Beltzhoover Mason", credit: "Gilbert Stuart", src: "/gallery/cma-1921-428.jpg", page: "https://clevelandart.org/art/1921.428" },
  { id: "cma-1963-91", label: "La Cervara, the Roman Campagna", credit: "Jean Baptiste Camille Corot", src: "/gallery/cma-1963-91.jpg", page: "https://clevelandart.org/art/1963.91" },
  { id: "cma-1942-645", label: "Portrait of the Ladies Amabel and Mary Jemima Yorke", credit: "Joshua Reynolds", src: "/gallery/cma-1942-645.jpg", page: "https://clevelandart.org/art/1942.645" },
  { id: "cma-1922-684", label: "Mount Starr King, Yosemite", credit: "Albert Bierstadt", src: "/gallery/cma-1922-684.jpg", page: "https://clevelandart.org/art/1922.684" },
  { id: "cma-1971-101", label: "Danaë", credit: "Orazio Gentileschi", src: "/gallery/cma-1971-101.jpg", page: "https://clevelandart.org/art/1971.101" },
  { id: "cma-1924-195", label: "Early Morning After a Storm at Sea", credit: "Winslow Homer", src: "/gallery/cma-1924-195.jpg", page: "https://clevelandart.org/art/1924.195" },
  { id: "cma-1936-19", label: "The Pigeon Tower at Bellevue", credit: "Paul Cezanne", src: "/gallery/cma-1936-19.jpg", page: "https://clevelandart.org/art/1936.19" },
  { id: "cma-1958-32", label: "Two Poplars in the Alpilles near Saint-Rémy", credit: "Vincent van Gogh", src: "/gallery/cma-1958-32.jpg", page: "https://clevelandart.org/art/1958.32" },
  { id: "cma-1942-1065", label: "Romaine Lacaux", credit: "Pierre-Auguste Renoir", src: "/gallery/cma-1942-1065.jpg", page: "https://clevelandart.org/art/1942.1065" },
  { id: "cma-1943-392", label: "The Call", credit: "Paul Gauguin", src: "/gallery/cma-1943-392.jpg", page: "https://clevelandart.org/art/1943.392" },
  { id: "cma-1934-29", label: "Virgin and Child", credit: "Hans Memling", src: "/gallery/cma-1934-29.jpg", page: "https://clevelandart.org/art/1934.29" },
  { id: "cma-1966-13", label: "Antiochus and Stratonice", credit: "Jean-Auguste-Dominique Ingres", src: "/gallery/cma-1966-13.jpg", page: "https://clevelandart.org/art/1966.13" },
  { id: "cma-1952-17", label: "George III", credit: "Benjamin West", src: "/gallery/cma-1952-17.jpg", page: "https://clevelandart.org/art/1952.17" },
  { id: "cma-1926-247", label: "The Holy Family with Mary Magdalen", credit: "El Greco", src: "/gallery/cma-1926-247.jpg", page: "https://clevelandart.org/art/1926.247" },
  { id: "cma-1926-25", label: "Orpheus", credit: "Odilon Redon", src: "/gallery/cma-1926-25.jpg", page: "https://clevelandart.org/art/1926.25" },
  { id: "cma-1971-166", label: "Terminus, the Device of Erasmus", credit: "Hans Holbein the Younger", src: "/gallery/cma-1971-166.jpg", page: "https://clevelandart.org/art/1971.166" },
  { id: "cma-1919-1018", label: "British Manufactory; A Sketch", credit: "Benjamin West", src: "/gallery/cma-1919-1018.jpg", page: "https://clevelandart.org/art/1919.1018" },
  { id: "cma-1947-207", label: "Portrait of Isabella Brant", credit: "Peter Paul Rubens", src: "/gallery/cma-1947-207.jpg", page: "https://clevelandart.org/art/1947.207" },
  { id: "cma-1975-263", label: "The Large Tree", credit: "Paul Gauguin", src: "/gallery/cma-1975-263.jpg", page: "https://clevelandart.org/art/1975.263" },
  { id: "cma-1944-524", label: "The Brierwood Pipe", credit: "Winslow Homer", src: "/gallery/cma-1944-524.jpg", page: "https://clevelandart.org/art/1944.524" },
  { id: "cma-1926-1653", label: "On the Beach, No. 3", credit: "Maurice Prendergast", src: "/gallery/cma-1926-1653.jpg", page: "https://clevelandart.org/art/1926.1653" },
  { id: "cma-1965-15", label: "Portrait of the Jester Calabazas", credit: "Diego Velázquez", src: "/gallery/cma-1965-15.jpg", page: "https://clevelandart.org/art/1965.15" },
  { id: "cma-1958-20", label: "The Brook", credit: "Paul Cezanne", src: "/gallery/cma-1958-20.jpg", page: "https://clevelandart.org/art/1958.20" },
  { id: "cma-1942-644", label: "A Young Man with a Chain", credit: "Rembrandt van Rijn", src: "/gallery/cma-1942-644.jpg", page: "https://clevelandart.org/art/1942.644" },
  { id: "cma-1967-215", label: "Composition with Red, Yellow, and Blue", credit: "Piet Mondrian", src: "/gallery/cma-1967-215.jpg", page: "https://clevelandart.org/art/1967.215" },
  { id: "cma-1927-437", label: "Madame Désiré Raoul-Rochette", credit: "Jean-Auguste-Dominique Ingres", src: "/gallery/cma-1927-437.jpg", page: "https://clevelandart.org/art/1927.437" },
  { id: "cma-1929-13", label: "Fighting Horses", credit: "Théodore Géricault", src: "/gallery/cma-1929-13.jpg", page: "https://clevelandart.org/art/1929.13" },
  { id: "cma-1964-420", label: "Panoramic View of the Alps, Les Dents du Midi", credit: "Gustave Courbet", src: "/gallery/cma-1964-420.jpg", page: "https://clevelandart.org/art/1964.420" },
  { id: "cma-1925-1409", label: "Monsieur Boileau at the Café", credit: "Henri de Toulouse-Lautrec", src: "/gallery/cma-1925-1409.jpg", page: "https://clevelandart.org/art/1925.1409" },
  { id: "cma-1930-23", label: "Capriccio: A Palace with a Courtyard by the Lagoon", credit: "Antonio Canaletto", src: "/gallery/cma-1930-23.jpg", page: "https://clevelandart.org/art/1930.23" },
  { id: "cma-1971-2", label: "Portrait of George Pitt, First Baron Rivers", credit: "Thomas Gainsborough", src: "/gallery/cma-1971-2.jpg", page: "https://clevelandart.org/art/1971.2" },
  { id: "cma-1958-34", label: "Berthe Morisot with a Muff", credit: "Édouard Manet", src: "/gallery/cma-1958-34.jpg", page: "https://clevelandart.org/art/1958.34" },
  { id: "cma-1954-128", label: "Boy with Anchor", credit: "Winslow Homer", src: "/gallery/cma-1954-128.jpg", page: "https://clevelandart.org/art/1954.128" },
  { id: "cma-1916-1044", label: "Gardener's House at Antibes", credit: "Claude Monet", src: "/gallery/cma-1916-1044.jpg", page: "https://clevelandart.org/art/1916.1044" },
  { id: "cma-1943-657", label: "Invocation to Love", credit: "Jean-Honoré Fragonard", src: "/gallery/cma-1943-657.jpg", page: "https://clevelandart.org/art/1943.657" },
  { id: "cma-1958-21", label: "Mount Sainte-Victoire", credit: "Paul Cezanne", src: "/gallery/cma-1958-21.jpg", page: "https://clevelandart.org/art/1958.21" },
  { id: "cma-1958-54", label: "May Belfort", credit: "Henri de Toulouse-Lautrec", src: "/gallery/cma-1958-54.jpg", page: "https://clevelandart.org/art/1958.54" },
  { id: "cma-1958-25", label: "Paul Lafond and Alphonse Cherfils Examining a Painting", credit: "Edgar Degas", src: "/gallery/cma-1958-25.jpg", page: "https://clevelandart.org/art/1958.25" },
  { id: "cma-1949-439", label: "Head of a Tahitian Woman", credit: "Paul Gauguin", src: "/gallery/cma-1949-439.jpg", page: "https://clevelandart.org/art/1949.439" },
  { id: "cma-1970-161", label: "Point Judith, Rhode Island", credit: "Martin Johnson Heade", src: "/gallery/cma-1970-161.jpg", page: "https://clevelandart.org/art/1970.161" },
  { id: "cma-1970-160", label: "Virgin and Child with the Young Saint John the Baptist", credit: "Sandro Botticelli", src: "/gallery/cma-1970-160.jpg", page: "https://clevelandart.org/art/1970.160" },
  { id: "cma-1984-59", label: "Rocky, Wooded Landscape with a Dell and Weir", credit: "Thomas Gainsborough", src: "/gallery/cma-1984-59.jpg", page: "https://clevelandart.org/art/1984.59" },
];
